---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=2.1.1
cache: bundler
#sudo: false
sudo: required
dist: trusty
before_install:
  - sudo apt-get update --assume-yes -qq
  - sudo apt-get install --assume-yes -qq python-apt python-pycurl
install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION

script:
  - echo -e "\e[31m######AnsibleVersion#######\e[0m"
  - sudo ansible --version

  # 0: install requirement
  - echo "\e[31m######***************************** REQUIREMENT (0) *****************************\e[0m"
  - sudo ansible-galaxy install --role-file requirements.yml

  # 1: syntax check
  - echo "\e[31m######***************************** SYNTAX (0) *****************************\e[0m"
  - sudo ansible-playbook --inventory-file tests/hosts --syntax-check tests/playbook.yml

  # 2: play role
  - echo "\e[31m######***************************** ROLE (0) *****************************\e[0m"
  - sudo ansible-playbook --inventory-file tests/hosts --connection=local -vvvv tests/playbook.yml
