---
# Download Oracle Java
#
# Installing Java while fetching the distribution from Oracle is
# a nightmare.
#
# Version information is a huge mess with Oracle Java. Naming of
# files, directories and zip archives is never consistent and one
# never knows what they are up to next.
#
# What this does is trying to use Ansible capabilities while
# allowing a usable installation of the Oracle Java JDK.


# Install a persistent local data path for ansible to manage
#   downloading Java.
- name: Install local ansible data path directory
  tags: java
  local_action: file
    state=directory
    owner=0
    group=0
    mode=2777
    dest={{ local_ansible_data_path }}


# Downloaded archives are verified with shasum command
- name: Install Java redis package sha256sum
  tags: java
  local_action: template
    src=sha256sum.j2
    dest={{ local_ansible_data_path }}/java.sha256sum

# Test whether we need to download Java (again).
- name: Verify Java redis package sha256sum
  tags: java
  ignore_errors: true
  failed_when: false
  register: java_oracle_redis_exists
  local_action: command
    shasum
      --algorithm 256
      --portable
      --check
      --status
      {{ local_ansible_data_path }}/java.sha256sum

# Ensure there is no broken download on the local disk
- name: Remove possible broken Java redis package
  tags:
    - java
    - download
  when: java_oracle_redis_exists.rc != 0
  local_action: file
    state=absent
    dest={{ local_ansible_data_path }}/{{ java_oracle_redis_filename }}

# Download the Java distribution from Oracle to the workstations'
# filesystem. Yeah, right, accept license agreement...
# This allows to distribute Java to any number of hosts in the
# context of a local network instead of downloading Java again
# for every role/node which depends on this role.
- name: Download Oracle Java redis package
  tags: java
  sudo: no
  register: java_oracle_redis_download
  when: java_oracle_redis_exists.rc != 0
  local_action: command
    curl
      --location
      --insecure
      --remote-name
      --cookie oraclelicense={{ java_oracle_curl_cookie }}
      --cookie-jar /tmp/{{ java_oracle_redis_filename }}.cookie
      {{ java_oracle_redis_mirror }}
    chdir={{ local_ansible_data_path }}
    creates={{ local_ansible_data_path }}/{{ java_oracle_redis_filename }}

# Fixup possible users umask issues
- name: Ensure downloaded archive is world readable
  tags: java
  local_action: file
    dest={{ local_ansible_data_path }}/{{ java_oracle_redis_filename }}
    mode=0644

# Test whether downloaded redistributable package passes sha256sum
- name: Verify Oracle Java redis package sha256sum
  tags: java
  when: java_oracle_redis_download|changed
  local_action: command
    shasum
      --algorithm 256
      --portable
      --check
      --status
      {{ local_ansible_data_path }}/java.sha256sum
