---
# Download Oracle Java
#
# Installing Java while fetching the distribution from Oracle is
# a nightmare.
#
# Version information is a huge mess with Oracle Java. Naming of
# files, directories and zip archives is never consistent and one
# never knows what they are up to next.
#
# What this does is trying to use Ansible capabilities while
# allowing a re-usable installation of the Oracle Java JDK.


# Downloaded archives are verified with shasum command
- name: Register shasum binary
  tags:
    - java
    - java_download
  changed_when: false
  register: java_registered_shasum_binary
  when: java_shasum_binary in (None, "")
  always_run: true
  with_first_found: java_shasum_binaries
  local_action: command true

- name: Configure shasum binary
  tags:
    - java
    - java_download
  always_run: true
  local_action: set_fact
  args:
    java_fact_shasum_binary: "{{ java_shasum_binary if java_shasum_binary not in (None, '') else java_registered_shasum_binary.results.0.item }}"


- name: Install Java redis packages sha256sum files
  tags:
    - java
    - java_download
  with_items:
    - java.sha256sum
    - java_jce.sha256sum
  local_action: template
  args:
    src: "{{ item }}.j2"
    dest: "{{ util_persistent_data_path_local }}/{{ item }}"
    mode: 0644


# Test whether we need to download Java (again).
- name: Verify Java redis package sha256sum
  tags:
    - java
    - java_download
  ignore_errors: true
  failed_when: false
  changed_when: false
  register: java_oracle_redis_exists
  always_run: true
  local_action: command
    {{ java_fact_shasum_binary }}
      --check
      --status
      {{ '--algorithm 256' if java_fact_shasum_binary|search('shasum') else '' }}
      {{ util_persistent_data_path_local }}/java.sha256sum

- name: Verify Java JCE redis package sha256sum
  tags:
    - java
    - java_download
  ignore_errors: true
  failed_when: false
  changed_when: false
  register: java_oracle_redis_jce_exists
  always_run: true
  local_action: command
    {{ java_fact_shasum_binary }}
      --check
      --status
      {{ '--algorithm 256' if java_fact_shasum_binary|search('shasum') else '' }}
      {{ util_persistent_data_path_local }}/java_jce.sha256sum


# Ensure there is no broken download on the local disk
- name: Remove possible broken Java redis package
  tags:
    - java
    - java_download
  when: java_oracle_redis_exists.rc != 0
  local_action: file
  args:
    state: absent
    dest: "{{ util_persistent_data_path_local }}/{{ java_oracle_redis_filename }}"

- name: Remove possible broken Java JCE redis package
  tags:
    - java
    - java_download
  when: java_oracle_redis_jce_exists.rc != 0
  local_action: file
  args:
    state: absent
    dest: "{{ util_persistent_data_path_local }}/{{ java_oracle_redis_jce_filename }}"


# Download the Java distribution from Oracle to the workstations'
# filesystem. Yeah, right, accept license agreement...
# This allows to distribute Java to any number of hosts in the
# context of a local network instead of downloading Java again
# for every role/node which depends on this role.
- name: Download Oracle Java redis package
  tags:
    - java
    - java_download
  register: java_oracle_redis_download
  when: java_oracle_redis_exists.rc != 0
  local_action: command
    curl
      --location
      --insecure
      --remote-name
      --cookie oraclelicense={{ java_oracle_curl_cookie }}
      --cookie-jar /tmp/{{ java_oracle_redis_filename }}.cookie
      {{ java_oracle_redis_mirror }}
  args:
    chdir: "{{ util_persistent_data_path_local }}"
    creates: "{{ util_persistent_data_path_local }}/{{ java_oracle_redis_filename }}"

- name: Download Oracle Java JCE redis package
  tags:
    - java
    - java_download
  register: java_oracle_redis_jce_download
  when: java_oracle_redis_jce_exists.rc != 0
  local_action: command
    curl
      --location
      --insecure
      --remote-name
      --cookie oraclelicense={{ java_oracle_curl_cookie }}
      --cookie-jar /tmp/{{ java_oracle_redis_filename }}.cookie
      {{ java_oracle_mirror_jce }}/{{ java_oracle_redis_jce_filename }}
  args:
    chdir: "{{ util_persistent_data_path_local }}"
    creates: "{{ util_persistent_data_path_local }}/{{ java_oracle_redis_jce_filename }}"

# Fixup possible users umask issues
- name: Ensure downloaded archives are world readable
  tags:
    - java
    - java_download
  with_items: ["{{ java_oracle_redis_filename }}", "{{ java_oracle_redis_jce_filename }}"]
  local_action: file
  args:
    dest: "{{ util_persistent_data_path_local }}/{{ item }}"
    mode: 0644

# Test whether downloaded redistributable package passes sha256sum
- name: Verify Oracle Java redis package sha256sum
  tags:
    - java
    - java_download
  when: java_oracle_redis_download|changed
  local_action: command
    {{ java_fact_shasum_binary }}
      --check
      --status
      {{ '--algorithm 256' if java_fact_shasum_binary|search('shasum') else '' }}
      {{ util_persistent_data_path_local }}/java.sha256sum

- name: Verify Java JCE redis package sha256sum
  tags:
    - java
    - java_download
  when: java_oracle_redis_jce_download|changed
  local_action: command
    {{ java_fact_shasum_binary }}
      --check
      --status
      {{ '--algorithm 256' if java_fact_shasum_binary|search('shasum') else '' }}
      {{ util_persistent_data_path_local }}/java_jce.sha256sum
